version: "3.8"

services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - my_network

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data
      - ./init-db/init.sql:/docker-entrypoint-initdb.d/init.sql # Load your SQL file
    networks:
      - my_network
    # healthcheck:
    #   test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
    #   interval: 10s
    #   retries: 5
    #   timeout: 5s

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
